# Generated by Django 2.2.26 on 2022-03-14 22:53

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conceptio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
