# Generated by Django 2.2.26 on 2022-03-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conceptio', '0002_auto_20220323_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
