# Generated by Django 2.2.26 on 2022-03-26 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceptio', '0004_auto_20220324_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Password')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='First_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conceptio.Category'),
        ),
    ]
