# Generated by Django 2.2.26 on 2022-03-28 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptio', '0004_auto_20220327_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.AlterField(
            model_name='project',
            name='cat',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Category'),
        ),
    ]
