# Generated by Django 2.2.26 on 2022-03-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conceptio', '0004_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
