# Generated by Django 2.2.26 on 2022-03-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptio', '0005_auto_20220328_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Username'),
        ),
    ]
