# Generated by Django 2.2.26 on 2022-03-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceptio', '0005_auto_20220326_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='dislikes',
        ),
        migrations.AlterField(
            model_name='project',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conceptio.Category'),
        ),
    ]
