# Generated by Django 2.2.26 on 2022-03-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptio', '0006_auto_20220326_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cat',
            field=models.CharField(max_length=120, verbose_name='Category'),
        ),
    ]
