# Generated by Django 2.2.26 on 2022-03-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptio', '0008_auto_20220327_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cat',
            field=models.CharField(blank=True, max_length=12000, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.CharField(max_length=30000, verbose_name='Description'),
        ),
    ]
