# Generated by Django 2.2.26 on 2022-03-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceptio', '0009_auto_20220328_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='cat',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Category'),
        ),
    ]
