# Generated by Django 2.2.26 on 2022-03-28 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conceptio', '0010_auto_20220328_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='First_name',
            new_name='first_name',
        ),
    ]
